@localBaseUrl = http://localhost:4004/srv
@localUser = admin
@localPassword = admin

###
# @name localCasGetResources
GET {{localBaseUrl}}/cas/resources
Authorization: Basic {{localUser}}:{{localPassword}}

###
# @name localCasGetResourcesForceRefresh
GET {{localBaseUrl}}/cas/resources(forceRefresh=true)
Authorization: Basic {{localUser}}:{{localPassword}}

###
# @name locaTmsGetLandscape
GET {{localBaseUrl}}/tms/landscape
Authorization: Basic {{localUser}}:{{localPassword}}
