//@tmsUrl = https://sapux.org/tms
// define tmsUrl, tokenUrl,  tmsClientId and tmsClientSecret in .vscode/settings.json -> rest-client.environmentVariables

### Get OAuth Token
# @name tmsLogin
POST {{tokenUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{tmsClientId}}&client_secret={{tmsClientSecret}}

###
# @name tmsGetNodes
GET {{tmsUrl}}/v2/nodes
Authorization: Bearer {{tmsLogin.response.body.access_token}}
Accept: application/json

###
# @name tmsGetRoutes
GET {{tmsUrl}}/v2/routes
Authorization: Bearer {{tmsLogin.response.body.access_token}}
Accept: application/json

###
# @name tmsGetTransportRequests
GET {{tmsUrl}}/v2/nodes/192836/transportRequests?status=in
Authorization: Bearer {{tmsLogin.response.body.access_token}}
Accept: application/json

###
# @name tmsFileUpload
POST {{tmsUrl}}/v2/files/upload
Authorization: Bearer {{tmsLogin.response.body.access_token}}
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="int-devops@sap-test.de"

int-devops@sap-test.de
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cpi-iflow.mtar"
Content-Type: application/zip

< ../upload/cpi-iflow.mtar
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name tmsFileDelete
DELETE {{tmsUrl}}/v2/files/{{tmsFileUpload.response.body.fileId}}
Authorization: Bearer {{tmsLogin.response.body.access_token}}
Accept: application/json

###
# @name tmsNodeExport
POST {{tmsUrl}}/v2/nodes/export
Authorization: Bearer {{tmsLogin.response.body.access_token}}
Accept: application/json
Content-Type: application/json

{
    "nodeName": "INT_DEV2",
    "contentType": "MTA",
    "storageType": "FILE", 
    "description": "Test Transport",
    "namedUser": "int-devops@sap-test.de",
    "entries": [
        {
            "uri": {{tmsFileUpload.response.body.fileId}}
        }
    ]
}